CATEGORY_CHOICES = (
    ('Romance', 'Romance'),
    ('Fantasy', 'Fantasy'),
    ('Science-Fiction', 'Science-Fiction'),
    ('Horror', 'Horror'),
    ('Mystery', 'Mystery'),
    ('Thriller', 'Thriller'),
    ('Fiction', 'Fiction'),
    ('Non-Fiction', 'Non-Fiction'),
    ('Biography', 'Biography'),
    ('Autobiography', 'Autobiography'),
    ('Memoir', 'Memoir'),
    ('Self-Help', 'Self-Help'),
    ('Health', 'Health'),
    ('Travel', 'Travel'),
    ('History', 'History'),
    ('Poetry', 'Poetry'),
    ('Cooking', 'Cooking'),
    ('Art', 'Art'),
    ('Philosophy', 'Philosophy'),
    ('Science', 'Science'),
    ('Technology', 'Technology'),
  
)